services:
  app:
    image: tasky-app
    container_name: tasky-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - tasky-network
  db:
    image: mongo:8.0
    container_name: tasky-db
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: cmerino # replace with your username
      MONGO_INITDB_ROOT_PASSWORD: secret # replace with your password
      MONGO_INITDB_DATABASE: tasky-db # replace with your database name
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 20s # every 20 seconds
      start_period: 15s # wait 15 seconds before starting to check
      retries: 5 # retry 5 times
      timeout: 5s # timeout for each check
    volumes:
      - mongo-data:/data/db
    networks:
      - tasky-network
networks:
  tasky-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local