apiVersion: v1
kind: ConfigMap
metadata:
  name: tasky-configmap
  namespace: tasky-dev
  labels:
    app: tasky
    version: v1.0.0
    environment: development
    tier: backend
spec:
  data:
    mongo_port: "27017"
    mongo_host: "mongo-service" # change to your mongo service name
    app_port: "8080"
    go_env: "testing"