apiVersion: v1
kind: Secret
metadata:
  name: tasky-secret
  namespace: dev
  labels:
    app: tasky
    version: v1.0.0
    environment: development
    tier: backend
    purpose: config
type: Opaque
data:
  # The key is the name of the secret, and the value is the base64 encoded value
  # The value is a base64 encoded string of "my-secret-value"
  mongo_username: cm9vdA==        # base64 encoded "root"
  mongo_password: dG9vcg==        # base64 encoded "toor"
  mongo_dbname: dGFza3ktZGI=      # base64 encoded "tasky-db"
