apiVersion: v1
kind: Secret
metadata:
  name: tasky-secret
  namespace: tasky-dev
  labels:
    app: tasky
    version: v1.0.0
    environment: development
    tier: backend
type: Opaque
data:
  # The key is the name of the secret, and the value is the base64 encoded value
  # The value is a base64 encoded string of "my-secret-value"
  mongo_username: dXNlcl9hZG1pbg==        # base64 encoded "user_admin"
  mongo_password: dXNlcl9wYXNzd29yZA==    # base64 encoded "user_password"
  mongo_dbname: dGFza3lfZGI=              # base64 encoded "tasky_db"
